### PR TITLE
Fixing icon placement.

### PR DESCRIPTION
**Pull request by jpodwys**
Fixing icon-placement introduced when `birch-typeahead` was hybridized.

@tylergraf

### CODE REVIEW

**Comment by tylergraf** [comment]
The dropdown icons look off.
image

**Comment by jpodwys** [comment]
Yes, this change is supposed to fix the issue you're seeing.

**Comment by tylergraf** [comment]
icon

**Comment by jpodwys** [comment]
OK should be fixed now.

**Comment by tylergraf** [comment]
Looks good. I don't have merge rights or I'd do it.

**Comment by jpodwys** [comment]
Thanks @tylergraf and @chadeddington

**Pull request merged**
