### PR TITLE
Match paper-item’s hybridized API by using “slot”.

### PR DESCRIPTION
**Pull request by jpodwys**
@tylergraf

### CODE REVIEW

**Comment by tylergraf** [comment]
This is what I'm seeing in firefox:
birch

**Comment by jpodwys** [comment]
As far as I can tell, that's actually the way it's working in FF before my changes. I'm not able to make it happen that way after applying my changes. Can you please make sure you're running the code from the `use-slot` branch?

**Comment by tylergraf** [comment]
Yeah, let me check.

**Comment by tylergraf** [comment]
Ok, looks good. I re cloned it.

**Pull request merged**
