### PR TITLE
Bug Fix: Correctly trap enter and escape

### PR DESCRIPTION
**Pull request by skye2k2**
Remove global preventDefaultActions--only stop propagation of enter and escape when the standards picker is shown.
Remove incorrect enter behavior & test--enter should never be captured when the standards picker is not shown.
Remove birch-typeahead:cancel handler (_handleCancel() was being called twice), so that keydown is handled before cancel.
Set _hideStandards property more accurately as state changes.
Add unit tests for correctly trapping enter and escape.

### CODE REVIEW

**Comment by skye2k2** [comment]
Lingering issue: After selecting the original text on an initial standards-picker flyout, going back and pressing down to re-open opens multiple standards-pickers.

lingering_issue

Everything else behaves as desired when integrated in fs-add-person (hide-standards-menu enabled)

**Comment by jpodwys** [comment]
@skye2k2 let's go over this together tomorrow.

**Comment by jpodwys** [comment]
Closing in favor of #48 and [this PR to `birch-typeahead`](https://github.com/FamilySearchElements/birch-typeahead/pull/9).

**Comment by skye2k2** [comment]
Thanks. The combination PR resolves my original concern and works in the add flow use case.

**Pull request closed without merging**
