### PR TITLE
2.0

### PR DESCRIPTION
**Pull request by jpodwys**
#### Feature Additions

* Handle data assignments so the component can be populated with previously selected content
* Add the `reset` function
* Add "Standard Selected" indicator (no longer show standards drop down when a standard is selected)
* Add "No standardized date/place is available." indicator (no longer show standards drop down when no standard is available)

#### Breaking Changes

* Merge the public API properties into a single `data` object
* Remove `julianDateRange` as this component has no use for it

#### Bug Fixes

* Use XHR instead of fetch so that network calls can be aborted. This prevents the race conditions associated with keeping track of whether the next network call response should be ignored via the `_stopSearch` bool
* When a user selects a standard from the standards drop down while a network call is pending, cancel the network call and respect their selection rather than ignoring their selection and waiting for the network call to complete
* Add the `object-assign-shim` for IE11 compatibility

#### Other

* Move CSS to a separate file
* Use `birch-typeahead`'s `debounceInputDuration` property
* Use the new `followTabindexAfterTabSelect` property from `birch-typeahead`
* Remove `_handleDownArrowForTypeahead` by adding it as a default behavior to `birch-typeahead`
* Separate the request and response handling logic

@dthorne

### CODE REVIEW

**Comment by jpodwys** [comment]
@dthorne I have yet to confirm that this component will actually hit `tree-data` in the appropriate environment. I haven't gotten a working `tree-data` proxy yet and the Memories app is still being converted to  `wc-i18n` v2 so I can't yet test it in the Gallery's context.

I'll let you know when I successfully test with a proxy. Until then, feel free to look at the changes.

**Comment by rosemariesadler** [comment]
Someone will need to verify this, but as I recall `julianDateRange` is a required value for tree when we submit our standards for saving.

**Comment by jpodwys** [comment]
I understand that, but the component itself doesn't need `julianDateRange` and it's simple enough to generate given the available options in the `data` property. Tree can generate it on the fly in their wrapper of `birch-standards-picker`.

**Comment by rosemariesadler** [comment]
Oh, I see - I thought you were removing it from the data based on the comments - looking at the code I see that it's still there, you just removed the component's property. Sorry about that.

**Comment by jpodwys** [comment]
No worries! If multiple teams end up wanting the property, we can add it to this component. But as of right now, Tree is the only team I'm aware of (of the three teams interested in using it--Tree, Memories, and Indexing) that needs `julianDateRange`.

**Pull request merged**
